apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-post
spec:
  replicas: 90
  selector:
    matchLabels:
      app: http-post
  template:
      metadata:
        labels:
          app: http-post
      spec:
        containers:
        - name: http-post
          image: gcr.io/praxis-road-382013/http_post:latest